# Generated by Django 5.0.2 on 2024-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
