# Generated by Django 5.0.2 on 2024-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hotelbooking_hotel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['hotel_name'], name='accounts_ho_hotel_n_31441d_idx'),
        ),
    ]
