# Generated by Django 5.0.2 on 2024-02-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hotel_accounts_ho_hotel_n_360675_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotel',
            name='accounts_ho_hotel_n_360675_idx',
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['hotel_name'], name='accounts_ho_hotel_n_31441d_idx'),
        ),
    ]
